# name of the site
name: Badoo Tech Blog

# description of the site used in feed.xml and in the header
description: Tech blog from the engineers behind Badoo.

# url of the production site
url: https://techblog.badoo.com

# format of the links - do not change this as it will break all existing links!
permalink: /blog/:year/:month/:day/:title/

# if less is available on the PATH and being compiled then set this to false to not minify the outputted css
compress_less: true

# this is set to true by the LessGenerator plugin if lessc is not available on the PATH
# in this case less.js is used to compile in the browser.
use_lessjs: false

# our shortname for the disqus plugin
disqus_shortname: badootechblog

# files to exclude
exclude: ["pom.xml", "assembly.xml", "target", "README.md"]

# Google Analytics tracking code and domain
google_analytics:
    code: UA-25578576-18
    domain: badoo.com

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts    # limit to posts
    values:
      type: posts